const strings = {
    en: {
        // General
        cancel: "Cancel",
        submit: "Submit",
        delete: "Delete",
        confirm: "Confirm",
        back: "Back",
        // Landing Page
        landing_choose_role: "Choose Your Role",
        landing_user_title: "I am a User",
        landing_user_desc: "Access my secure account.",
        landing_analyst_title: "I am an Analyst",
        landing_analyst_desc: "Monitor fraud activity.",
        // Login
        login_title: "Welcome",
        login_subtitle: "Enter your PIN to access your account.",
        login_phone_placeholder: "Phone Number",
        login_pin_placeholder: "6-Digit PIN",
        login_button: "Login",
        login_incorrect_pin: "Incorrect PIN. Please try again.",
        // Onboarding
        onboarding_title: "Welcome to SafiShield",
        onboarding_consent_text: "For enhanced security, this app uses on-device biometrics (Face or Voice). Your biometric data is encrypted and never leaves your phone. You can manage or delete it at any time in the settings.",
        onboarding_accept: "Accept & Continue",
        onboarding_decline: "Decline & use PIN only",
        // Dashboard
        dashboard_greeting: "Welcome",
        dashboard_balance: "Available Balance",
        dashboard_security_status: "Security Status",
        dashboard_status_secure: "Secure",
        dashboard_status_warning: "Warning",
        dashboard_status_risk: "High Risk",
        // Quick Actions
        action_send: "Send",
        action_withdraw: "Withdraw",
        action_history: "History",
        action_biometrics: "Biometrics",
        action_report_scam: "Report Scam",
        action_settings: "Settings",
        // Nav
        nav_home: "Home",
        nav_send: "Send",
        nav_history: "History",
        nav_biometrics: "Biometrics",
        // Send Money
        send_money_title: "Send Money",
        send_money_recipient: "Recipient Agent",
        send_money_amount: "Amount (KES)",
        send_money_note: "Note (Optional)",
        send_money_button: "Send Money",
        // Withdraw
        withdraw_title: "Withdraw Money",
        withdraw_agent: "Select Agent",
        withdraw_button: "Withdraw",
        // History
        history_title: "Transaction History",
        history_no_transactions: "No transactions yet.",
        // Biometrics
        biometrics_title: "Manage Biometrics",
        biometrics_enroll_face: "Enroll Face",
        biometrics_enroll_voice: "Enroll Voice",
        biometrics_face_enrolled: "Face Enrolled",
        biometrics_voice_enrolled: "Voice Enrolled",
        biometrics_enrolled_on: "Enrolled on",
        biometrics_not_enrolled: "Not Enrolled",
        biometrics_delete: "Delete",
        biometrics_re_enroll: "Re-enroll",
        biometrics_consent_needed: "You must provide consent for biometrics in settings to use this feature.",
        // Settings
        settings_title: "Settings",
        settings_manage_biometrics: "Manage Biometrics",
        settings_change_pin: "Change PIN",
        settings_privacy: "Privacy",
        settings_delete_data: "Delete My Data",
        settings_delete_data_confirm: "Are you sure? This will permanently delete all your local data, including profile, transactions, and biometric templates. This action cannot be undone.",
        settings_language: "Language",
        settings_theme: "App Theme",
        settings_theme_system: "System",
        settings_theme_light: "Light",
        settings_theme_dark: "Dark",
        settings_theme_high_contrast: "High Contrast",
        settings_large_font: "Large Font Size",
        settings_biometrics_consent: "Allow On-Device Biometrics",
        // Report Scam
        report_scam_title: "Report a Scam",
        report_scam_phone: "Scammer's Phone Number",
        report_scam_message: "Scam Message (Copy/Paste)",
        report_scam_type: "Type of Scam",
        report_scam_type_phishing: "Phishing",
        report_scam_type_loan: "Loan Scam",
        report_scam_type_prize: "Fake Prize",
        report_scam_submit: "Submit Report",
        report_scam_success: "Scam reported successfully. Thank you!",
    },
    sw: {
        // General
        cancel: "Ghairi",
        submit: "Wasilisha",
        delete: "Futa",
        confirm: "Thibitisha",
        back: "Rudi",
        // Landing Page
        landing_choose_role: "Chagua Jukumu Lako",
        landing_user_title: "Mimi ni Mtumiaji",
        landing_user_desc: "Fikia akaunti yangu salama.",
        landing_analyst_title: "Mimi ni Mchambuzi",
        landing_analyst_desc: "Fuatilia shughuli za ulaghai.",
        // Login
        login_title: "Karibu",
        login_subtitle: "Weka PIN yako kufungua akaunti.",
        login_phone_placeholder: "Nambari ya Simu",
        login_pin_placeholder: "PIN ya dijiti 6",
        login_button: "Ingia",
        login_incorrect_pin: "PIN si sahihi. Jaribu tena.",
        // Onboarding
        onboarding_title: "Karibu SafiShield",
        onboarding_consent_text: "Kwa usalama zaidi, programu hii hutumia bayometriki (Uso au Sauti) kwenye kifaa chako. Taarifa zako za kibayometriki husimbwa kwa njia fiche na hazitoki kwenye simu yako. Unaweza kuzidhibiti au kuzifuta wakati wowote kwenye mipangilio.",
        onboarding_accept: "Kubali na Endelea",
        onboarding_decline: "Kataa na utumie PIN pekee",
        // Dashboard
        dashboard_greeting: "Karibu",
        dashboard_balance: "Salio Lako",
        dashboard_security_status: "Hali ya Usalama",
        dashboard_status_secure: "Salama",
        dashboard_status_warning: "Tahadhari",
        dashboard_status_risk: "Hatari Kubwa",
        // Quick Actions
        action_send: "Tuma",
        action_withdraw: "Toa",
        action_history: "Historia",
        action_biometrics: "Bayometriki",
        action_report_scam: "Ripoti Ulaghai",
        action_settings: "Mipangilio",
        // Nav
        nav_home: "Mwanzo",
        nav_send: "Tuma",
        nav_history: "Historia",
        nav_biometrics: "Bayometriki",
        // Send Money
        send_money_title: "Tuma Pesa",
        send_money_recipient: "Wakala Mpokeaji",
        send_money_amount: "Kiasi (KES)",
        send_money_note: "Ujumbe (Si lazima)",
        send_money_button: "Tuma Pesa",
        // Withdraw
        withdraw_title: "Toa Pesa",
        withdraw_agent: "Chagua Wakala",
        withdraw_button: "Toa Pesa",
        // History
        history_title: "Historia ya Miamala",
        history_no_transactions: "Hakuna miamala bado.",
        // Biometrics
        biometrics_title: "Dhibiti Bayometriki",
        biometrics_enroll_face: "Sajili Uso",
        biometrics_enroll_voice: "Sajili Sauti",
        biometrics_face_enrolled: "Uso Umesajiliwa",
        biometrics_voice_enrolled: "Sauti Imesajiliwa",
        biometrics_enrolled_on: "Imesajiliwa tarehe",
        biometrics_not_enrolled: "Haijasajiliwa",
        biometrics_delete: "Futa",
        biometrics_re_enroll: "Sajili Upya",
        biometrics_consent_needed: "Unahitaji kutoa idhini ya bayometriki kwenye mipangilio ili kutumia kipengele hiki.",
        // Settings
        settings_title: "Mipangilio",
        settings_manage_biometrics: "Dhibiti Bayometriki",
        settings_change_pin: "Badilisha PIN",
        settings_privacy: "Faragha",
        settings_delete_data: "Futa Data Yangu",
        settings_delete_data_confirm: "Una uhakika? Hii itafuta kabisa data zako zote za ndani, ikiwa ni pamoja na wasifu, miamala, na violezo vya bayometriki. Kitendo hiki hakiwezi kutenduliwa.",
        settings_language: "Lugha",
        settings_theme: "Mwonekano wa Programu",
        settings_theme_system: "Mfumo",
        settings_theme_light: "Mwangaza",
        settings_theme_dark: "Giza",
        settings_theme_high_contrast: "Mguso Mkali",
        settings_large_font: "Ukubwa wa herufi",
        settings_biometrics_consent: "Ruhusu Bayometriki Kifaa",
        // Report Scam
        report_scam_title: "Ripoti Ulaghai",
        report_scam_phone: "Nambari ya Simu ya Mlaghai",
        report_scam_message: "Ujumbe wa Ulaghai (Nakili/Bandika)",
        report_scam_type: "Aina ya Ulaghai",
        report_scam_type_phishing: "Uvuvi wa Data",
        report_scam_type_loan: "Ulaghai wa Mikopo",
        report_scam_type_prize: "Zawadi Bandia",
        report_scam_submit: "Tuma Ripoti",
        report_scam_success: "Ulaghai umeripotiwa. Asante!",
    },
    fr: {
        // General
        cancel: "Annuler",
        submit: "Soumettre",
        delete: "Supprimer",
        confirm: "Confirmer",
        back: "Retour",
        // Landing Page
        landing_choose_role: "Choisissez Votre Rôle",
        landing_user_title: "Je suis un Utilisateur",
        landing_user_desc: "Accéder à mon compte sécurisé.",
        landing_analyst_title: "Je suis un Analyste",
        landing_analyst_desc: "Surveiller l'activité de fraude.",
        // Login
        login_title: "Bienvenue",
        login_subtitle: "Entrez votre PIN pour accéder à votre compte.",
        login_phone_placeholder: "Numéro de téléphone",
        login_pin_placeholder: "PIN à 6 chiffres",
        login_button: "Connexion",
        login_incorrect_pin: "PIN incorrect. Veuillez réessayer.",
        // Onboarding
        onboarding_title: "Bienvenue sur SafiShield",
        onboarding_consent_text: "Pour une sécurité renforcée, cette application utilise la biométrie sur l'appareil (Visage ou Voix). Vos données biométriques sont chiffrées et ne quittent jamais votre téléphone. Vous pouvez les gérer ou les supprimer à tout moment dans les paramètres.",
        onboarding_accept: "Accepter et Continuer",
        onboarding_decline: "Refuser et utiliser le PIN uniquement",
        // Dashboard
        dashboard_greeting: "Bienvenue",
        dashboard_balance: "Solde Disponible",
        dashboard_security_status: "État de la Sécurité",
        dashboard_status_secure: "Sécurisé",
        dashboard_status_warning: "Avertissement",
        dashboard_status_risk: "Risque Élevé",
        // Quick Actions
        action_send: "Envoyer",
        action_withdraw: "Retirer",
        action_history: "Historique",
        action_biometrics: "Biométrie",
        action_report_scam: "Signaler",
        action_settings: "Paramètres",
        // Nav
        nav_home: "Accueil",
        nav_send: "Envoyer",
        nav_history: "Historique",
        nav_biometrics: "Biométrie",
        // Send Money
        send_money_title: "Envoyer de l'argent",
        send_money_recipient: "Agent Bénéficiaire",
        send_money_amount: "Montant (KES)",
        send_money_note: "Note (Optionnel)",
        send_money_button: "Envoyer de l'argent",
        // Withdraw
        withdraw_title: "Retirer de l'argent",
        withdraw_agent: "Choisir un agent",
        withdraw_button: "Retirer",
        // History
        history_title: "Historique des Transactions",
        history_no_transactions: "Aucune transaction pour le moment.",
        // Biometrics
        biometrics_title: "Gérer la Biométrie",
        biometrics_enroll_face: "Enregistrer le Visage",
        biometrics_enroll_voice: "Enregistrer la Voix",
        biometrics_face_enrolled: "Visage Enregistré",
        biometrics_voice_enrolled: "Voix Enregistrée",
        biometrics_enrolled_on: "Enregistré le",
        biometrics_not_enrolled: "Non enregistré",
        biometrics_delete: "Supprimer",
        biometrics_re_enroll: "Ré-enregistrer",
        biometrics_consent_needed: "Vous devez donner votre consentement pour la biométrie dans les paramètres pour utiliser cette fonction.",
        // Settings
        settings_title: "Paramètres",
        settings_manage_biometrics: "Gérer la Biométrie",
        settings_change_pin: "Changer le PIN",
        settings_privacy: "Confidentialité",
        settings_delete_data: "Supprimer Mes Données",
        settings_delete_data_confirm: "Êtes-vous sûr ? Cela supprimera définitivement toutes vos données locales, y compris le profil, les transactions et les modèles biométriques. Cette action est irréversible.",
        settings_language: "Langue",
        settings_theme: "Thème de l'App",
        settings_theme_system: "Système",
        settings_theme_light: "Clair",
        settings_theme_dark: "Sombre",
        settings_theme_high_contrast: "Contraste Élevé",
        settings_large_font: "Grande Taille de Police",
        settings_biometrics_consent: "Autoriser la Biométrie sur l'Appareil",
        // Report Scam
        report_scam_title: "Signaler une Arnaque",
        report_scam_phone: "Numéro de l'Arnaqueur",
        report_scam_message: "Message de l'Arnaque (Copier/Coller)",
        report_scam_type: "Type d'Arnaque",
        report_scam_type_phishing: "Hameçonnage",
        report_scam_type_loan: "Arnaque au Prêt",
        report_scam_type_prize: "Faux Gain",
        report_scam_submit: "Envoyer le Signalement",
        report_scam_success: "Arnaque signalée avec succès. Merci !",
    }
};

export type Language = keyof typeof strings;
export type StringKeys = keyof typeof strings['en'];

export const getTranslation = (lang: Language) => (key: StringKeys): string => {
    return strings[lang]?.[key] || strings['en'][key];
};